"""
Порядок взаємодії:
  client (авторизований ApiClient)
        ├── created_app
        │     ├── created_segment
        │     │     ├── created_campaign
        │     │     └── created_funnel
        │     └── created_stream
        │           └── created_client
        └── random_uuid (хелпер)
"""

import json
import uuid
import pytest
from pathlib import Path

from clients.api_client import ApiClient
from config.settings import TEST_EMAIL, TEST_PASSWORD

FIXTURES_DIR = Path(__file__).parent / "data"


def load_fixture(name: str) -> dict:
    path = FIXTURES_DIR / f"{name}.json"
    with open(path, encoding="utf-8") as f:
        return json.load(f)

# ---------------------------------------------------------------------------
# API-клиенты
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def client() -> ApiClient:
    c = ApiClient()
    c.login(TEST_EMAIL, TEST_PASSWORD)
    return c


@pytest.fixture(scope="session")
def fx_auth():
    data = load_fixture("auth")
    data["valid"] = {
        "email": TEST_EMAIL,
        "password": TEST_PASSWORD,
    }
    return data

@pytest.fixture(scope="session")
def fx_apps():
    return load_fixture("apps")

@pytest.fixture(scope="session")
def fx_clients():
    return load_fixture("clients")

@pytest.fixture(scope="session")
def fx_segments():
    return load_fixture("segments")

@pytest.fixture(scope="session")
def fx_campaigns():
    return load_fixture("campaigns")

@pytest.fixture(scope="session")
def fx_funnels():
    return load_fixture("funnels")

@pytest.fixture(scope="session")
def fx_streams():
    return load_fixture("streams")

@pytest.fixture(scope="session")
def fx_push_messages():
    return load_fixture("push_messages")

@pytest.fixture(scope="session")
def created_app(client, fx_apps) -> dict:
    resp = client.post("/apps/sync", json=fx_apps["sync_new"])
    assert resp.status_code in (200, 201), \
        f"Failed to sync app: {resp.status_code} — {resp.text}"
    data = resp.json().get("data", {})
    assert data.get("id"), "App ID missing in sync response"
    yield data
    client.delete(f"/apps/{data['id']}")


@pytest.fixture(scope="session")
def created_segment(client, created_app, fx_segments) -> dict:
    payload = {**fx_segments["valid"], "app_id": created_app["id"]}
    resp = client.post("/segments", json=payload)
    assert resp.status_code == 201, \
        f"Failed to create segment: {resp.status_code} — {resp.text}"
    body = resp.json()
    data = body.get("data", body)
    assert data.get("id"), "Segment ID missing in response"
    yield data
    client.delete(f"/segments/{data['id']}")


@pytest.fixture(scope="session")
def created_push_message(client, created_app, fx_push_messages) -> dict:
    payload = {**fx_push_messages["valid"], "app_id": created_app["id"]}
    resp = client.post("/push-messages", json=payload)
    assert resp.status_code == 201, \
        f"Failed to create push message: {resp.status_code} — {resp.text}"
    data = resp.json().get("data", resp.json())
    assert data.get("id"), "Push message ID missing in response"
    yield data
    client.delete(f"/push-messages/{data['id']}")


@pytest.fixture(scope="session")
def created_campaign(client, created_app, created_segment, created_push_message) -> dict:
    payload = {
        "app_id": created_app["id"],
        "segment_id": created_segment["id"],
        "push_message_id": created_push_message["id"],
        "name": "Autogenerated Test Campaign",
    }
    resp = client.post("/campaigns", json=payload)
    assert resp.status_code == 201, \
        f"Failed to create campaign: {resp.status_code} — {resp.text}"
    body = resp.json()
    data = body.get("data", {}).get("campaign", body.get("data", body))
    assert data.get("id"), "Campaign ID missing in response"
    yield data
    client.delete(f"/campaigns/{data['id']}")


@pytest.fixture(scope="session")
def created_funnel(client, created_app, created_segment, fx_funnels) -> dict:
    payload = {
        **fx_funnels["valid"],
        "app_id": created_app["id"],
        "segment_id": created_segment["id"],
    }
    resp = client.post("/funnels", json=payload)
    assert resp.status_code == 201, \
        f"Failed to create funnel: {resp.status_code} — {resp.text}"
    data = resp.json().get("data", {})
    assert data.get("id"), "Funnel ID missing in response"
    yield data
    client.delete(f"/funnels/{data['id']}")


@pytest.fixture(scope="session")
def created_stream(client, created_app, fx_streams) -> dict:
    payload = {**fx_streams["valid"], "app_bundle": created_app["bundle"]}
    resp = client.post("/streams", json=payload)
    assert resp.status_code == 201, \
        f"Failed to create stream: {resp.status_code} — {resp.text}"
    data = resp.json().get("data", {})
    assert data.get("id") or data.get("uid"), "Stream ID/UID missing in response"
    yield data
    uid = data.get("uid") or data.get("id")
    client.delete(f"/streams/{uid}")


@pytest.fixture(scope="session")
def created_client(client, created_app, created_stream, fx_clients) -> dict:
    stream_uid = created_stream.get("uid") or created_stream.get("id")
    payload = {
        **fx_clients["valid"],
        "id": str(uuid.uuid4()),
        "push_token": f"TestToken_{uuid.uuid4().hex}",
        "bundle": created_app["bundle"],
        "stream_uid": stream_uid,
    }
    resp = client.post("/clients", json=payload)
    assert resp.status_code == 201, \
        f"Failed to create client: {resp.status_code} — {resp.text}"
    data = resp.json().get("data", {})
    assert data.get("id"), "Client ID missing in response"
    yield data


@pytest.fixture
def random_uuid() -> str:
    return str(uuid.uuid4())
